### ISSUE TITLE
Document static has configuration

### ISSUE THREAD

**Issue by dylans** [dojo/has#19]
Should we document how to configure a has value, or is this the correct/only approach:

`add('my-feature', false, true);`

**Comment by kitsonk** [comment]
Is the README of [static features](https://github.com/dojo/has#static-features) not sufficient?

This was part of the PR that made the feature work, so that might be why you didn't notice it.

**Comment by dylans** [comment]
Yes, this content was not present before in master and I didn't see the PR, so I'll close.
